### ISSUE TITLE
does this work for node tokens?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/token_filter#2]
[In this issue](https://github.com/backdrop/backdrop-issues/issues/944) I reported my failure to port this very module. Did I get that wrong? Wouldn't be surprised as wasn't sure what I was doing.

**Comment by jerry-hudgins** [comment]
The Drupal module only guarantees that global tokens will be replaced. Its description states:

> The module now supports native tokens (e.g. [site:name]) and all global tokens by default. It even allows some contextual tokens like node or user to be replaced, but currently does not encourage users to use them in the filter help text.

It sounds as though node (and user) tokens were unreliable even in D7, and I didn't attempt to make them work in Backdrop.

**Comment by docwilmot** [comment]
Youre right, if I'd read that, I would have finished the port years ago then. 😃
