### ISSUE TITLE
Call to nonexistent function token_get_entity_mapping()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/token_filter#3]
On line 39 of token_filter.module, there is a call to token_get_entity(). If this point is reached in the code, the module crashes because that function doesn't exist in the Backdrop version of token module.

A quick-and-dirty patch that works is to copy token_get_entity_mapping() from the D7 token module into this module and {drupal-->backdrop}-ize it. But there undoubtedly more to do than that to fix this properly.

**Comment by jerry-hudgins** [comment]
Thanks for the report. Someone else will need to field this issue, however, as I'm no longer working in web development.

**Comment by bugfolder** [comment]
I'm willing to take over as maintainer of the module. Are you OK with that? Would you want to remain a co-maintainer?

**Comment by jerry-hudgins** [comment]
Absolutely, and thanks. There's no point to my being retained as a co-maintainer. If I need to take some action to transfer the ownership, let me know. I don't have any GitHub experience with that.

If you have the interest and bandwidth, please consider assuming maintainership of the simple [HSTS module](https://github.com/backdrop-contrib/hsts) as well.

**Comment by bugfolder** [comment]
OK, I'll take over as maintainer of Token Filter. I'll follow [the process for taking over](https://backdropcms.org/user-guide/adopt-a-project).

Regarding HSTS module, that's beyond me right now, but if you're not going to be the maintainer going forward, perhaps you could update the README file under "Current Maintainer" to say "Seeking maintainer", which would then alert interested parties that they could take over?

**Comment by jerry-hudgins** [comment]
Thanks!

**Comment by herbdool** [comment]
Transfer looks good. Now just need someone with permissions to fix this project's. @klonos or @jenlampton?

**Comment by bugfolder** [comment]
Transfer is done, PRs merged for revised README file and bugfix for this issue.
