### ISSUE TITLE
Deprecated drupal function &drupal_static in token_filter.module

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/token_filter#9]
Deprecated function `&drupal_static` is called on line 81 of  `token_filter.module`

https://github.com/backdrop-contrib/token_filter/blob/9cdddb1a42dfb247c82c11a41333104d30eda84f/token_filter.module#L81

See [deprecation notice](https://docs.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/function/drupal_static/1)

PR to follow

**Comment by argiepiano** [comment]
Bitten by this again. The current version of Token Filter doesn't contain this PR... Any chance to do a new release?
